blank_issues_enabled: false
contact_links:
  - name: 📖 项目文档
    url: https://github.com/starknt/blive#readme
    about: 查看项目文档和使用指南
  - name: 💬 讨论区
    url: https://github.com/starknt/blive/discussions
    about: 在讨论区提问或分享想法
