no-clearly-defined = true
private = { ignore = true }
accepted = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "Apache-2.0 WITH LLVM-exception",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "CC0-1.0",
    "NCSA",
    "Unicode-3.0",
    "OpenSSL",
    "Zlib",
    "CDLA-Permissive-2.0",
    "0BSD"
]

[gpui-component.clarify]
license = "MIT"

[gpui-component-macros.clarify]
license = "MIT"

[tree-sitter-graphql.clarify]
license = "MIT"
